name: Build and Push to ECR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push app image
        run: |
          docker build -t clo835-a1-app ./app
          docker tag clo835-a1-app:latest 851725360313.dkr.ecr.us-east-1.amazonaws.com/clo835-a1-app:latest
          docker push 851725360313.dkr.ecr.us-east-1.amazonaws.com/clo835-a1-app:latest

      - name: Build, tag, and push db image
        run: |
          docker build -t clo835-a1-db ./db
          docker tag clo835-a1-db:latest 851725360313.dkr.ecr.us-east-1.amazonaws.com/clo835-a1-db:latest
          docker push 851725360313.dkr.ecr.us-east-1.amazonaws.com/clo835-a1-db:latest
